### ISSUE TITLE
Allow for blog, portfolio, etc. pages to be optional

### ISSUE THREAD

**Issue by tofumatt** [octopusthink/ghost-ship#12]
@sarahmonster was working on https://github.com/octopusthink/funfactsaboutoctopus.es and found that simply removing the `src/content/blog/` folders wasn't sufficient to hide the blog functionality. We should separate the queries we make for blog posts vs pages and only build/render the blog content if there are posts to make.

**Comment by sarahmonster** [comment]
Making this modular would be ideal, so anyone can add and remove post types easily. And by "anyone", obviously I mean me.
