### ISSUE TITLE
Switch to non-relative import paths

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/ghost-ship#14]
So 

> import App from ‘./app’;

should be

> import App from ‘./App’;

otherwise things will panic and fail to build. Sadface.

While we're at it, it'd be good to switch to non-relative paths as per https://github.com/octopusthink/octopusthink.com/pull/88

**Comment by tofumatt** [comment]
The case-awareness is a macOS thing (it doesn't have a case-aware filesystem), but the import path fixing is a definitive "yes".

**Comment by sarahmonster** [comment]
Right, what I meant is that the code in Ghost Ship should use capitalisation that matches the actual filenames, otherwise things will break when it builds. See https://github.com/octopusthink/ghost-ship/blob/86504ebfa075aee03d5abdd11808a63368775df8/src/templates/Page.js#L7 and a number of other places.

**Comment by tofumatt** [comment]
Oh, snap, yes. Totally!
