### ISSUE TITLE
Add super-simple site structure

### ISSUE THREAD

**Issue by sarahmonster** [octopusthink/ghost-ship#27]
This will both show how to use CSS in a site, and also avoid this super ugly thing:

<img width="1131" alt="Screenshot 2019-12-28 at 23 07 48" src="https://user-images.githubusercontent.com/376315/71550381-eaeebf80-29c6-11ea-8aa6-8dd0b35cdf37.png">

Just some sort of max-width on the main content area should do the trick.

**Comment by tofumatt** [comment]
Yeah, that's fair. I did nothing with the base content, but some simple skeleton would be good 👍

**Comment by sarahmonster** [comment]
A lot of starter themes don't bother, but that's always sort of driven me bananas and it means it's always the first thing I do when starting up a new site. Giving a bit of a baseline structure makes it a little bit easier to get up and running with something, and it's easy enough to remove. See #32 for a suggested approach!

**Comment by tofumatt** [comment]
Especially as we're building this for us _first_, I agree. Some kind of starter is great.
